### PR TITLE
Create homepage

### LINKED ISSUE #8: As a user I want to see the Homepage
# Description
Basic home page is created for user

# Acceptance Criteria
- Home page is created
- Basic information about the application is generated

# Testing
- Click the hosting link
- The home page should appear immediately upon opening

### PR DESCRIPTION
**Pull request by LinhNguyenLe2109**
image

Created home page
Updated tailwind config file
Install react-router, there is an issue with this library right now where I'm unable to do nested routing, will revisit this in the future

### CODE REVIEW

**Comment by leoschwartz** [comment]
The page styling looks good, maybe the title text could be more concise.
Where will the get started button take the user?
And I noticed that tsx files are being used, just be aware that the react app was created in Js so there is no tsconfig file.

**Review by pstaleystudent — CHANGES_REQUESTED** [review]
I don't think we need an unauthenticated homepage - we're not trying to sell to clients through the management software itself. This should probably just be a placeholder for now

**Comment by LinhNguyenLe2109** [comment]
Yeah good idea, I thought about this one as well but I'm not sure if having a home page is better or not. I think I would keep it like this and in the future we switch this one to the dashboard for authenticated users

**Comment by pstaleystudent** [comment]
Yeah that's fine

**Pull request merged**
